module.exports={

REDEEM_POINTS_SUCCESS:"REDEM_POINTS_SUCCESS",
REDEEM_POINTS_FAILURE:"REDEM_POINTS_FAILURE",
RESET_REDEEM_POINTS:"RESET_REDEEM_POINTS",
LOGIN_SUCCESS:"LOGIN_SUCCESS",
LOGIN_FAILURE:"LOGIN_FAILURE",
USER_EMAIL:"USER_EMAIL"
};